/*
 * Copyright Lamont Granquist, Sebastien Gaggini and the MechJeb contributors
 * SPDX-License-Identifier: LicenseRef-PD-hp OR Unlicense OR CC0-1.0 OR 0BSD OR MIT-0 OR MIT OR LGPL-2.1+
 */

using System.Runtime.CompilerServices;
using static MechJebLib.Utils.Statics;
using static System.Math;

/*
 * Interpolated initial guess for Russell's vercosine Lambert solver, following:
 *
 *   Russell, R. P. "Complete Lambert Solver Including Second-Order Sensitivities."
 *   Journal of Guidance, Control, and Dynamics 45.2 (2022): 196-212, Section II.C-D.
 *
 * The geometry tau and the time of flight are transformed to x and y (and z = ln N for
 * multi-rev) such that the solution k is defined on a rectangle (Algorithms 1-3 of the
 * paper).  The rectangle is adaptively split in half along a fixed per-level pattern of
 * dimensions, forming a binary tree, and a polynomial of fixed total order is fit in each
 * leaf bin.  The zero-rev table fits k, like the paper.  Unlike the paper, the multi-rev
 * table fits the log of the ratio of the distances of k from the bottom of the time of
 * flight curve and from the limit of the branch (see MultiRevTarget), which keeps the
 * guess on the requested branch and relatively accurate close to both ends of it.
 *
 * The multi-rev solver needs kBottom, the k at the minimum time of flight, which is solved
 * for with a Newton iteration.  Like the paper, which interpolates the minimum time of flight
 * instead, it is seeded from a table over x and z.
 *
 * The tables in RussellGuessTables.cs are generated by Tools/RussellTableGenerator from
 * our own solutions of Lambert's equation.
 */

// ReSharper disable InconsistentNaming
namespace MechJebLib.Lambert
{
    internal static partial class RussellGuess
    {
        // Algorithm 1: |x| = 1 when |tau| is 1e-7 from sqrt(2)/2
        internal const double C5 = 0.06340542125108602;

        // Algorithm 2: |y| = 0 when Gamma = 1e-7 N and |y| = 1 when Gamma ~ 6e5 N
        internal const double C1    = 0.03398904681649696;
        internal const double C2    = 0.5478387076731984;
        internal const double EPS_A = 1e-16;

        // Algorithm 3: y = 0 when the time of flight is 1e-3 times the parabolic time of flight
        internal const double C6                  = -6.907755278982137; // ln(1e-3)
        internal const double BETA_KINK           = -11.8286415451763;  // x = -0.75
        internal const double GAMMA_MAX_SLOPE_POS = 9.0 / 16.0;
        internal const double GAMMA_MAX_SLOPE_NEG = 1.183567863353605;
        internal const double GAMMA_MAX_INTERCEPT = 15.0;
        internal const double GAMMA_MAX_FLAT      = 1.0;

        // multi-rev guesses for N > N_MAX use the N_MAX boundary
        internal const int N_MAX = 3000;

        /// <summary>
        ///     Initial guess for k for the zero-rev problem.
        /// </summary>
        /// <param name="tau">The geometry parameter, |tau| &lt; sqrt(2)/2</param>
        /// <param name="tofbyS">The time of flight normalized by S</param>
        internal static double ZeroRev(double tau, double tofbyS)
        {
            double beta = Beta(tau);
            double x = Clamp(C5 * beta, -1.0, 1.0);
            double y = Clamp(ZeroRevY(tau, beta, tofbyS), 0.0, 1.0);
            return _zeroRev.Evaluate2(x, y);
        }

        /// <summary>
        ///     The geometry variable x, clamped to the tables (Algorithm 1).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double X(double tau) => Clamp(C5 * Beta(tau), -1.0, 1.0);

        /// <summary>
        ///     The revolutions variable z, clamped to the tables.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double Z(int nabs) => Log(Min(nabs, N_MAX));

        /// <summary>
        ///     Initial guess for kBottom, the k at the minimum time of flight for the multi-rev problem.
        /// </summary>
        /// <param name="tau">The geometry parameter, |tau| &lt; sqrt(2)/2</param>
        /// <param name="x">The geometry variable, from <see cref="X" /></param>
        /// <param name="z">The revolutions variable, from <see cref="Z" /></param>
        /// <param name="nabs">Number of full revolutions</param>
        internal static double KBottom(double tau, double x, double z, int nabs) =>
            KBottomFromTarget(_kBottom.Evaluate2(x, z), Russell.KBottomAsymptotic(tau), nabs);

        /// <summary>
        ///     Initial guess for k for the multi-rev problem.
        /// </summary>
        /// <param name="x">The geometry variable, from <see cref="X" /></param>
        /// <param name="z">The revolutions variable, from <see cref="Z" /></param>
        /// <param name="gamma">The time of flight normalized by S, minus the minimum for this number of revolutions</param>
        /// <param name="nrev">Number of full revolutions (+ long-period, - short-period)</param>
        /// <param name="kBottom">The k at the minimum time of flight for this number of revolutions</param>
        internal static double MultiRev(double x, double z, double gamma, int nrev, double kBottom) =>
            MultiRevFromTarget(_multiRev.Evaluate3(x, MultiRevY(gamma, nrev), z), nrev, kBottom);

        /// <summary>
        ///     The multi-rev table fits the log of the ratio of the distance of k from kBottom to its distance from the
        ///     limit of the branch (sqrt(2) for long-period and -sqrt(2) for short-period), so that the guess is relatively
        ///     accurate both close to the minimum time of flight and for very long times of flight, and is always strictly
        ///     on the requested branch.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double MultiRevTarget(double k, int nrev, double kBottom) =>
            nrev > 0 ? Log((k - kBottom) / (SQRT2 - k)) : Log((kBottom - k) / (k + SQRT2));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double MultiRevFromTarget(double q, int nrev, double kBottom)
        {
            double e1 = 1.0 + Exp(q);
            return nrev > 0 ? SQRT2 - (SQRT2 - kBottom) / e1 : (kBottom + SQRT2) / e1 - SQRT2;
        }

        /// <summary>
        ///     The k-bottom table fits N (kBottom - kBottomInf), where kBottomInf is the limit of kBottom as N -> infinity.
        ///     This approaches a constant as N grows, so dividing by N extrapolates it beyond N_MAX.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double KBottomTarget(double kBottom, double kBottomInf, int nabs) => nabs * (kBottom - kBottomInf);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double KBottomFromTarget(double q, double kBottomInf, int nabs) => kBottomInf + q / nabs;

        /// <summary>
        ///     Log scaled distance of tau from the r1 == r2 singularity at |tau| = sqrt(2)/2 (Algorithm 1).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double Beta(double tau) => -Sign(tau) * Log(1.0 - SQRT2 * Abs(tau));

        /// <summary>
        ///     The parabolic time of flight normalized by S (Russell 2019, Eq. 39).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double ParabolicTofbyS(double tau) => Sqrt(1.0 - SQRT2 * tau) * (tau + SQRT2) / 3.0;

        /// <summary>
        ///     Upper bound of ln(TOF / TOF_parabolic) for the zero-rev table, as a function of beta (Algorithm 3).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double GammaBarMaxZeroRev(double beta)
        {
            if (beta > 0.0)
                return GAMMA_MAX_SLOPE_POS * beta + GAMMA_MAX_INTERCEPT;
            if (beta < BETA_KINK)
                return GAMMA_MAX_FLAT;
            return GAMMA_MAX_SLOPE_NEG * beta + GAMMA_MAX_INTERCEPT;
        }

        /// <summary>
        ///     The zero-rev flight time variable y, unclamped (Algorithm 3).
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double ZeroRevY(double tau, double beta, double tofbyS) =>
            (Log(tofbyS / ParabolicTofbyS(tau)) - C6) / (GammaBarMaxZeroRev(beta) - C6);

        /// <summary>
        ///     The multi-rev flight time variable y, clamped to the table (Algorithm 2).  The sign of y is the sign of nrev.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static double MultiRevY(double gamma, int nrev)
        {
            double g = Clamp(C1 * Log(gamma / Abs(nrev)) + C2, EPS_A, 1.0);
            return nrev > 0 ? g : -g;
        }

        /// <summary>
        ///     The geometry parameter tau for the geometry variable x (the inverse of <see cref="X" />).
        /// </summary>
        internal static double TauFromX(double x) => Sign(x) * -ExpM1(-Abs(x) / C5) / SQRT2;

        /// <summary>
        ///     The zero-rev time of flight normalized by S for the variables x and y (the inverse of <see cref="ZeroRevY" />).
        /// </summary>
        internal static double ZeroRevTofbyS(double x, double y)
        {
            double tau = TauFromX(x);
            double gammaBarMax = GammaBarMaxZeroRev(x / C5);
            return ParabolicTofbyS(tau) * Exp(C6 + y * (gammaBarMax - C6));
        }

        /// <summary>
        ///     The multi-rev time of flight normalized by S, minus the minimum, for the variable y (the inverse of
        ///     <see cref="MultiRevY" />).
        /// </summary>
        internal static double MultiRevGamma(double y, int nabs) => nabs * Exp((Abs(y) - C2) / C1);

        private static double ExpM1(double x) => Abs(x) < 1e-5 ? x + 0.5 * x * x + x * x * x / 6.0 : Exp(x) - 1.0;

        /// <summary>
        ///     A 2D polynomial of total order <paramref name="order" />, sum over i + j &lt;= order of c_ij u^i v^j,
        ///     with the coefficients stored with i in the outer loop and j in the inner loop.
        /// </summary>
        internal static double Poly2(double[] c, int offset, int order, double u, double v)
        {
            // Horner's method in u over Horner's method in v, walking the coefficients backwards
            int idx = offset + (order + 1) * (order + 2) / 2 - 1;
            double result = 0.0;
            for (int i = order; i >= 0; i--)
            {
                double q = c[idx--];
                for (int j = order - i; j > 0; j--)
                    q = q * v + c[idx--];
                result = result * u + q;
            }

            return result;
        }

        /// <summary>
        ///     A 3D polynomial of total order <paramref name="order" />, sum over i + j + l &lt;= order of c_ijl u^i v^j w^l,
        ///     with the coefficients stored with i in the outer loop and l in the inner loop.
        /// </summary>
        internal static double Poly3(double[] c, int offset, int order, double u, double v, double w)
        {
            // Horner's method in u over Horner's method in v over Horner's method in w, walking the coefficients backwards
            int idx = offset + (order + 1) * (order + 2) * (order + 3) / 6 - 1;
            double result = 0.0;
            for (int i = order; i >= 0; i--)
            {
                double qi = 0.0;
                for (int j = order - i; j >= 0; j--)
                {
                    double q = c[idx--];
                    for (int l = order - i - j; l > 0; l--)
                        q = q * w + c[idx--];
                    qi = qi * v + q;
                }

                result = result * u + qi;
            }

            return result;
        }

        /// <summary>
        ///     A binary tree of bins over a rectangular domain with a polynomial fit in each leaf.  Each level of the
        ///     tree splits its bins in half along the dimension given by the pattern for that level.  Bins in the tree
        ///     are stored such that for an internal node j the children (lower half first) are at Tree[j] and Tree[j] + 1,
        ///     and for a leaf node ~Tree[j] is the index of its coefficient block.
        /// </summary>
        internal sealed class Table
        {
            public readonly int      Dims;
            public readonly int      Order;
            public readonly byte[]   Pattern;
            public readonly double[] Lo;
            public readonly double[] Hi;
            public readonly int[]    Tree;
            public readonly double[] Coefs;
            public readonly int      CoefsPerBin;

            // the number of splits along each dimension, and the scale from the domain to the cells of the finest grid
            private readonly int[]    _splits;
            private readonly double[] _scale;

            // for each level, the bit of the cell index along its dimension which selects the lower or upper half
            private readonly int[] _shift;

            // for each dimension (major) and depth, the shift from the cell index to the index of the bin along that
            // dimension, and the width of the bins
            private readonly int[]    _binShift;
            private readonly double[] _width;

            public Table(int dims, int order, byte[] pattern, double[] lo, double[] hi, int[] tree, double[] coefs)
            {
                Dims    = dims;
                Order   = order;
                Pattern = pattern;
                Lo      = lo;
                Hi      = hi;
                Tree    = tree;
                Coefs   = coefs;

                CoefsPerBin = dims == 2 ? (order + 1) * (order + 2) / 2 : (order + 1) * (order + 2) * (order + 3) / 6;

                _splits = new int[dims];
                foreach (byte d in pattern)
                    _splits[d]++;

                _scale = new double[dims];
                for (int d = 0; d < dims; d++)
                    _scale[d] = (1 << _splits[d]) / (hi[d] - lo[d]);

                int levels = pattern.Length + 1;
                _shift    = new int[pattern.Length];
                _binShift = new int[dims * levels];
                _width    = new double[dims * levels];

                var used = new int[dims];
                for (int depth = 0; depth < levels; depth++)
                {
                    for (int d = 0; d < dims; d++)
                    {
                        _binShift[d * levels + depth] = _splits[d] - used[d];
                        _width[d * levels + depth]    = (hi[d] - lo[d]) / (1 << used[d]);
                    }

                    if (depth < pattern.Length)
                        _shift[depth] = _splits[pattern[depth]] - 1 - used[pattern[depth]]++;
                }
            }

            // the index of the cell of the finest grid along dimension d
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private int Cell(int d, double v) => Clamp((int)((v - Lo[d]) * _scale[d]), 0, (1 << _splits[d]) - 1);

            // the coordinate in [-1, 1] of v in its bin along dimension d, for a leaf at the given depth
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private double Local(int d, int depth, int cell, double v)
            {
                int k = d * (Pattern.Length + 1) + depth;
                double w = _width[k];
                return 2.0 * (v - Lo[d] - (cell >> _binShift[k]) * w) / w - 1.0;
            }

            public double Evaluate2(double x, double y)
            {
                int i0 = Cell(0, x);
                int i1 = Cell(1, y);

                int node = 0;
                int depth = 0;
                int t;
                while ((t = Tree[node]) >= 0)
                {
                    int cell = Pattern[depth] == 0 ? i0 : i1;
                    node = t + ((cell >> _shift[depth]) & 1);
                    depth++;
                }

                return Poly2(Coefs, ~t * CoefsPerBin, Order, Local(0, depth, i0, x), Local(1, depth, i1, y));
            }

            public double Evaluate3(double x, double y, double z)
            {
                int i0 = Cell(0, x);
                int i1 = Cell(1, y);
                int i2 = Cell(2, z);

                int node = 0;
                int depth = 0;
                int t;
                while ((t = Tree[node]) >= 0)
                {
                    byte d = Pattern[depth];
                    int cell = d == 0 ? i0 : d == 1 ? i1 : i2;
                    node = t + ((cell >> _shift[depth]) & 1);
                    depth++;
                }

                return Poly3(Coefs, ~t * CoefsPerBin, Order, Local(0, depth, i0, x), Local(1, depth, i1, y), Local(2, depth, i2, z));
            }
        }
    }
}
