/*
 * Copyright Lamont Granquist, Sebastien Gaggini and the MechJeb contributors
 * SPDX-License-Identifier: LicenseRef-PD-hp OR Unlicense OR CC0-1.0 OR 0BSD OR MIT-0 OR MIT OR LGPL-2.1+
 */
﻿using System;
using System.Reflection;
using UnityEngine;

namespace MechJebLibBindings
{
    public static class ReflectionUtils
    {
        public static readonly bool IsLoadedProceduralFairing;
        public static readonly bool IsLoadedRealFuels;
        public static readonly bool IsLoadedRealismOverhaul;
        public static readonly bool IsLoadedPrincipia;
        public static readonly bool IsLoadedFAR;

        static ReflectionUtils()
        {
            IsLoadedProceduralFairing = IsAssemblyLoaded("ProceduralFairings");
            IsLoadedRealFuels         = IsAssemblyLoaded("RealFuels");
            IsLoadedPrincipia         = IsAssemblyLoaded("principia.ksp_plugin_adapter");
            IsLoadedFAR               = IsAssemblyLoaded("FerramAerospaceResearch");
            IsLoadedRealismOverhaul   = IsAssemblyLoaded("RealismOverhaul");
        }

        public static bool IsAssemblyLoaded(string assemblyName)
        {
            foreach (AssemblyLoader.LoadedAssembly assembly in AssemblyLoader.loadedAssemblies)
            {
                try
                {
                    if (assembly.assembly.GetName().Name == assemblyName)
                    {
                        return true;
                    }
                }
                catch (InvalidOperationException)
                {
                    // Silently drop exception generated by users who manage to put assembly that
                    // can't load for reasons (missing deps most of the time)
                }
            }

            return false;
        }

        public static FieldInfo? GetFieldByReflection(string assemblyString, string className, string fieldName,
            BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static)
        {
            string assemblyName = "";

            foreach (AssemblyLoader.LoadedAssembly loaded in AssemblyLoader.loadedAssemblies)
            {
                if (loaded.assembly.GetName().Name == assemblyString)
                {
                    assemblyName = loaded.assembly.FullName;
                }
            }

            if (assemblyName == "")
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find assembly " + assemblyString);
                return null;
            }

            var type = Type.GetType(className + ", " + assemblyName);

            if (type == null)
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find type  " + className + ", " + assemblyName);
                return null;
            }

            return type.GetField(fieldName, flags);
        }

        public static MethodInfo? GetMethodByReflection(string assemblyString, string className, string methodName, BindingFlags flags)
        {
            string assemblyName = "";

            foreach (AssemblyLoader.LoadedAssembly loaded in AssemblyLoader.loadedAssemblies)
            {
                if (loaded.assembly.GetName().Name == assemblyString)
                {
                    assemblyName = loaded.assembly.FullName;
                }
            }

            if (assemblyName == "")
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find assembly " + assemblyString);
                return null;
            }

            var type = Type.GetType(className + ", " + assemblyName);

            if (type == null)
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find type  " + className + ", " + assemblyName);
                return null;
            }

            return type.GetMethod(methodName, flags);
        }

        public static MethodInfo? GetMethodByReflection(string assemblyString, string className, string methodName, BindingFlags flags, Type[] args)
        {
            string assemblyName = "";

            foreach (AssemblyLoader.LoadedAssembly loaded in AssemblyLoader.loadedAssemblies)
            {
                if (loaded.assembly.GetName().Name == assemblyString)
                {
                    assemblyName = loaded.assembly.FullName;
                }
            }

            if (assemblyName == "")
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find assembly " + assemblyString);
                return null;
            }

            var type = Type.GetType(className + ", " + assemblyName);

            if (type == null)
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find type  " + className + ", " + assemblyName);
                return null;
            }

            return type.GetMethod(methodName, flags, null, args, null);
        }

        public static Type? GetClassByReflection(string assemblyString, string className)
        {
            string assemblyName = "";

            foreach (AssemblyLoader.LoadedAssembly loaded in AssemblyLoader.loadedAssemblies)
            {
                if (loaded.assembly.GetName().Name == assemblyString)
                {
                    assemblyName = loaded.assembly.FullName;
                }
            }

            if (assemblyName == "")
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find assembly " + assemblyString);
                return null;
            }

            var type = Type.GetType(className + ", " + assemblyName);

            if (type == null)
            {
                Debug.Log("[MechJeb] ReflectionUtils: could not find type  " + className + ", " + assemblyName);
                return null;
            }

            return type;
        }
    }
}
